name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: install node modules
        run: yarn

      - name: run linter
        run: yarn lint

      - name: run e2e testing
        run: yarn e2e

      - name: check if it builds
        run: yarn build

      - name: build docker image
        run: docker build . -t theed

