name: Docker

on:
  push:
    branches:
      - "canon"
      - "next"
    workflow_dispatch:

  pull_request:
    branches:
      - "canon"
      - "next"
    workflow_dispatch:

env:
  APP_VERSION: 0.4.0

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 18.7

      - run: npm install

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.LOGIN_DOCKERHUB_TEST }}
          password: ${{ secrets.PASSWORD_DOCKERHUB_TEST }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: bogdzn/theed

      - name: Build and push canon Docker image
        if: github.ref == 'refs/heads/canon' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: bogdzn/theed:canon, bogdzn/theed:${{ env.APP_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push dev docker image
        if: github.ref == 'refs/heads/next' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: bogdzn/theed:${{ env.APP_VERSION }}-dev, bogdzn/theed:dev
          labels: ${{ steps.meta.outputs.labels }}
