name: run e2e tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node:version: '18.7.0'

      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ${{env.working-directory}}
          build: yarn build
          start: yarn run
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
