name: run e2e tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run cypress tests
        uses: cypress-io/github-action@v4
        with:
          install-command: yarn --frozen-lockfile --silent
          build: yarn build

          start: yarn run
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120

          browser: chrome
