name: UT
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: install node modules
        run: npm install

      - name: run linter
        run: npm run lint

      - name: run tests
        run: npm run test
      
      - name: Fail if exit code is not 0
        if: steps.script.outputs.exitCode != 0
        run: fail "Exit code was not 0"